Removed All References of ElasticSearch and Updated Architecure
CMSgov/macpro-quickstart-serverless pull request #162
Opened 2021-04-08 18:50 UTC by ayoneeyee

## Purpose

This issue is to remove all components ElasticSearch from the quickstart. While there's nothing wrong with the ES implementation here, and while it demonstrates how to have another system plug into a data stream, it's slowing MAPro down. The projects that fork this repository are not in the market for ES. And if they were, the ES service would (hopefully) be a separate project that plugs into any number of data streams from Kafka (instead of DynamoDB Streams). The SES emailer functions are seen as a sufficient example of how to build event driven business logic while being lightweight; these emailers should remain. The ES service is a bigger and more expensive example of this, and isn't worth it for us.

#### Linked Issues to Close

Closes #131 
Closes #125 

## Approach
Searched and removed all references of Elastic search in the local repo.
Updated the Architectur.png to remove elasticsearch and associated connections
All ElasticSearch services, components, and support has been removed.

Some of the files removed include:
services/elasticsearch-auth/package.json
services/elasticsearch-auth/yarn.lock
services/elasticsearch/package.json
services/elasticsearch/yarn.lock
services/stream-functions/package.json
services/stream-functions/yarn.lock

## Learning
Removed Elasticsearch from the quickstart serverless repo. Then also removed all references of elasticsearch from other files and directories in the following repo. 
Reviewed logs to make sure there are no error and build completed successfully.
https://github.com/CMSgov/macpro-quickstart-serverless/tree/master/services

## Assorted Notes/Considerations
Make sure to review Github Action logs in details for any issue.
Existing environment will need Elasticsearch and Elasticsearch-auth deleted manually.
Updated the JIRA Ticket of updates and changes

#### Pull Request Creator Checklist

- [x] This PR has an associated issue or issues.
- [x] The associated issue(s) are linked above.
- [x] This PR meets all acceptance criteria for those issues.
- [x] This PR and linked issue(s) are adequately documented
- [x] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.
- [x] Someone has been assigned this PR.
- [x] At least one person has been marked as reviewer on this PR.

#### Pull Request Reviewer/Assignee Checklist

- [x] This PR has an associated issue or issues.
- [x] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.

2021-04-09 09:03 UTC, mdial89f requested changes
I have made two inline comments on this review, both of which call for changes. 

In addition to those two, there are two more changes that I'll list here... I'm not able to make these comments inline:
- The LambdaElasticSearchIndexerRole needs to be removed from the stream-functions service, as function that used it has been removed.
- Please remove the "Closes #125" from your PR.  The updates to the arch diagram are not what I had thought they were.  I gave you guidance earlier that you should add closing language to your PR for #125 , since your PR was going to accomplish/close that issue as well.  However, the diagram updates here, while accurate, are just updating the existing .png file.  That's OK, but it's not accomplishing the acceptance criteria of #125

2021-04-09 21:01 UTC, ayoneeyee commented on services/stream-functions/handlers/elasticsearchIndexer.js
> -const { pushStream } = require("dynamodb-stream-elasticsearch");
I removed the file as requested

2021-04-09 21:01 UTC, ayoneeyee commented on services/stream-functions/yarn.lock
> -"@elastic/elasticsearch@7.7.1":
Re-installed yarn to resolve issue

2021-04-12 12:02 UTC, mdial89f approved these changes

2021-04-12 12:02 UTC, merged