Pointing to remote serverless plugins
CMSgov/macpro-quickstart-serverless pull request #306
Opened 2021-09-02 02:54 UTC by joeaero19

## Purpose

Currently, we have the three plugins in a top level plugins directory.The top level package.json specifies these plugins as a dev dependency. Instead of specifying a version to fetch and install from npm, the package.json points to the local file path of the plugin source.
The three plugins have been moved into three new repositories, each having its own repo. This will allow this project and other projects to use these plugins without having the plugins' source code copied into each repo.

This PR points serverless-iam-helper, serverless-idempotency-helper and serverless-s3-bucket-helper to  their remote github repositories (https://github.com/CMSgov/cms-serverless-iam-helper, https://github.com/CMSgov/cms-serverless-idempotency-helper, https://github.com/CMSgov/cms-serverless-s3-bucket-helper )

issue link: https://github.com/CMSgov/macpro-quickstart-serverless/issues/300

#### Linked Issues to Close
Closes #304 

## Approach
Yarn remove command was used to remove the 3 plugins and yarn add command was used to add the new remote plugins as follows:
Yarn add CMSgov/repository_name 

#### Pull Request Creator Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.
- [ ] Someone has been assigned this PR.
- [ ] At least one person has been marked as reviewer on this PR.

#### Pull Request Reviewer/Assignee Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.

2021-09-02 09:56 UTC, mdial89f requested changes

2021-09-02 13:02 UTC, joeaero19 commented on package.json
> +    "serverless-iam-helper": "CMSgov/serverless-iam-helper",
done!

2021-09-02 13:34 UTC, mdial89f approved these changes

2021-09-02 16:32 UTC, merged

2021-09-07 13:50 UTC, macrael commented
Awesome